route:
  group_by: ['alertname', 'job']

  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: "https://discord.com/api/webhooks/1177651164095971369/V4WItv81NQwFC4bcugsBN3ywJP2yaFhFH2B-ocKKgtYLwWKm09ZYwZV37WuYiyAd887F"
